---
title: "Causal Impact in R with Advertising Data"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    toc_collapsed: true
  pdf_document:
      toc: true
      number_sections: true
  theme: lumen
---
# Things to do
Define the end of calibration period date properly
Try using ZUID instead of fullvisitorid
Try using a longer time period to account for seasonality


# Introduction

This R Markdown document serves as a guide to introduce users to show a POC for LTV

# Required packages
```{r}

library(tidyverse)
library(BTYD)
library(bigrquery)
```

```{r}
start_date = '2018-12-01'
end_date = '2019-02-10'
cohort_end_date = '2018-12-30'
end_of_cal_period = '2019-01-10'

project <- "zsgp-ga-bigq"
targets_dataset <- "94892991"

get_target_query <- paste0(
   "SELECT
  *
FROM
  (
  SELECT
    date,
    fullVisitorId as cust,
    totals.transactionRevenue/1000000 as sales,
    totals.transactions
     FROM `zsgp-ga-bigq.94892991.ga_sessions_*`
    where _TABLE_SUFFIX BETWEEN FORMAT_DATE('%Y%m%d', DATE('", start_date, "'))
    AND FORMAT_DATE('%Y%m%d', DATE('", end_date, "'))
  and
    totals.transactions IS NOT NULL
    ) a
JOIN
  (
  SELECT
    fullVisitorId
  FROM `zsgp-ga-bigq.94892991.ga_sessions_*`
    where _TABLE_SUFFIX BETWEEN FORMAT_DATE('%Y%m%d', DATE('", start_date, "'))
    AND FORMAT_DATE('%Y%m%d', DATE('", cohort_end_date, "'))
  and
    totals.newVisits IS NOT NULL
  #  AND RAND() < 1/50
  GROUP BY
    1
    ) b
ON
  a.cust=b.fullVisitorId
ORDER BY
  date"
  )

target_data <-
  bq_table_download(bq_project_query(project, get_target_query))

library(fst)
write.fst(target_data, "zlra_sg_btyd.fst")
elog <- read.fst("zlra_sg_btyd.fst")

```

## Build a BTYD model

You can also embed plots, for example:

```{r}
elog <- elog %>% 
  mutate_at(vars(sales), funs(replace(., is.na(.), 0))) %>% 
  filter(sales > 0)

elog <- data.frame(cust = elog$cust, date = elog$date, sales = elog$sales)
#elog$sales <- elog$sales / 10^6

# format dates
elog$date <- as.Date(elog$date, "%Y%m%d")

# set key dates
end.of.cal.period <- as.Date(end_of_cal_period)
T.end <- max(elog$date)
T.star <- as.numeric(T.end - end.of.cal.period)
T.tot <- as.numeric(max(elog$date) - min(elog$date))

dataset <- dc.ElogToCbsCbt(elog, per="day", 
  T.cal=end.of.cal.period)

# estimate model
# https://stackoverflow.com/questions/26280683/error-btyd-pnbd-estimateparameters-l-bfgs-b-needs-finite-values-of-fn
cal.cbs <- dataset[["cal"]][["cbs"]]
params <- pnbd.EstimateParameters(cal.cbs)
# params <- bgnbd.EstimateParameters(cal.cbs)

print(params)
```

```{r}
mape <- function(actual, forecasted) {
    n <- length(actual)
    (1/n) * sum(abs((actual - forecasted) / actual))
}

# calculate incremental and cumulative vectors
T.cal <- cal.cbs[,3]
actual.inc.tracking.data <- cbind(dataset[['cal']][['cbt']], 
  dataset[['holdout']][['cbt']])
actual.inc.tracking.data <- apply(actual.inc.tracking.data, 2, sum)
actual.cum.tracking.data <- cumsum(actual.inc.tracking.data)
expected.cum.trans <- pnbd.ExpectedCumulativeTransactions(params, T.cal, T.tot, length(actual.cum.tracking.data))

# find end of calibration date
end.of.cal.day <- as.numeric(end.of.cal.period - min(elog$date))

total.mape <- mape(actual.cum.tracking.data, expected.cum.trans)
in.sample.mape <- mape(actual.cum.tracking.data[1:end.of.cal.day], expected.cum.trans[1:end.of.cal.day])
out.of.sample.mape <- mape(actual.cum.tracking.data[end.of.cal.day:T.tot], expected.cum.trans[end.of.cal.day:T.tot])
mape.outputs <- data.frame("MAPE"=c(in.sample.mape, out.of.sample.mape, total.mape))
row.names(mape.outputs) <- c("In sample", "Out of sample", "Total")
print(mape.outputs)

```


# Analyse the model

```{r}
print(round(pnbd.Expectation(params, t=365), digits=1))
pnbd.PlotFrequencyInCalibration(params, cal.cbs, 7)
```

